---
- name: Install Autoware Control
  hosts: localhost
  connection: local
  vars:
    rosdep_install_dependency_types:
      - buildtool
      - exec
      - doc
      - buildtool_export
      - build_export
      - build
      - test

  roles:
    - role: bounverif.ros.repositories
    - role: bounverif.ros.file_operations
    # - role: bounverif.ros.rosdep_install
    - role: bounverif.ros.colcon_build
