- name: Install Autoware build dependencies 
  become: true
  ansible.builtin.apt:
    update_cache: true
    name:
      - build-essential
      - cmake
      - ccache
      - libboost-all-dev
      - libpcl-dev
      - libcgal-dev
      - libopencv-dev
      - libfmt-dev
      - libcrypto++-dev
      - libcpprest-dev
      - libpugixml-dev
      - libyaml-cpp-dev
      - librange-v3-dev

- include_role:
    name: bouncmpe.autoware.depend_rmw_implementation

- include_role:
    name: bouncmpe.autoware.depend_pacmod
