---
- name: Build Autoware and dependencies
  hosts: localhost
  connection: local
  vars:
    ros_distro: humble
    autoware_version: main
    autoware_ws: /workspaces/autoware
    autoware_src: "{{ autoware_ws }}/src"
    autoware_install_dir: "/opt/autoware/{{ ros_distro }}"

  roles:
    - role: bouncmpe.autoware.build_colcon
