---
- name: Prepare Autoware devel environment
  hosts: localhost
  connection: local
  vars:
    ros_distro: humble
    ros_distro_type: desktop
    autoware_version: main
    autoware_ws: /workspaces/autoware
    autoware_src: "{{ autoware_ws }}/src"
    autoware_install_dir: "{{ autoware_ws }}/install"

  roles:
    - role: bouncmpe.autoware.build_depend
    - role: bouncmpe.autoware.get_repository
    - role: bouncmpe.autoware.get_core_repos
    - role: bouncmpe.autoware.get_universe_repos
    - role: bouncmpe.autoware.get_build_deps_rosdep