name: autoware_diff_build

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/autoware_diff_build.yml # Self-trigger

jobs:
  build-and-test-differential:
    runs-on: ubuntu-latest
    container: ghcr.io/bounverif/autoware-prebuilt:latest

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: Check out repository
        uses: actions/checkout@v3
        with:
          repository: 'autowarefoundation/autoware'
          path: 'autoware'

      - name: Clone dependency packages
        run: |
          mkdir -p /src
          vcs import --shallow /src < autoware/autoware.repos
        shell: bash

      - name: Build
        run: |
          colcon build \
            --base-paths /src \
            --build-base /build \
            --install-base /install \
            --cmake-args -DCMAKE_BUILD_TYPE=Release \
        shell: bash
