name: autoware_diff_build

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/autoware_diff_build.yml # Self-trigger

jobs:
  autoware-diff-build:
    runs-on: ubuntu-latest
    container: ghcr.io/bounverif/autoware-prebuilt:latest

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: Check out repository
        uses: actions/checkout@v3
        with:
          repository: 'autowarefoundation/autoware'
          path: 'autoware'

      - run: mv autoware /autoware # https://github.com/actions/checkout/issues/197

      - name: Clone dependency packages
        run: |
          mkdir -p /autoware/src
          vcs import --shallow /autoware/src < /autoware/autoware.repos
        shell: bash

      - name: Build
        run: |
          . /opt/ros/humble/setup.sh
          colcon build \
            --base-paths /autoware/src \
            --build-base /autoware/build \
            --install-base /opt/autoware/humble/ \
            --cmake-args \
              " -Wno-dev" \
              " --no-warn-unused-cli" \
              -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
              -DCMAKE_C_COMPILER_LAUNCHER=ccache \
              -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
        shell: bash
        